---
title: <br><br> Accessibility statement
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    includes:
       in_header: tracking.html
---

<style type="text/css">

.footer{
  position: relative; 
  margin-top: 100px; 
  height = 100px; 
  width: 100%;
  text-align: left
}

.
</style>

<div class="call-to-action">This website is run by the DfE, MoJ and Home Office. We want as many people as possible to be able to use this website. For example, that means you should be able to:
<ul>
<li>change colours, contrast levels and fonts</li>
<li>zoom in up to 300% without the text spilling off the screen</li>
<li>navigate most of the website using just a keyboard</li>
<li>navigate most of the website using speech recognition software</li>
<li>listen to most of the website using a screen reader (including the most recent versions of JAWS, NVDA and VoiceOver)</li>
</ul>
<p>We've also made the website text as simple as possible to understand.</p>
<p><a href="https://mcmw.abilitynet.org.uk/" style="color: DARKBLUE;"><b>AbilityNet</b></a> has advice on making your device easier to use if you have a disability.</p>
</div>

<h3 id="how-accessible-this-website-is">How accessible this website is</h3>
<div class="call-to-action">We know some parts of this website are not fully accessible:</div>
<div class="call-to-action">
<ul>
<li>the tab names in the browser needs informative title tags</li>
<li>a focus state is required to increase the constrast when using the tab key</li>
<li>the website needs a "skip content" tab so that the tab doesn’t scroll through everything at the top before going further down the page</li>
<li>the floating menu on the left hand side in sections 2-5 needs to be keyboard accessible</li>
<li>the menu bar we requires a visually hidden text that says “menu”</li>
<li>we need to define language (= English) for each HTML page for the benefit of a screen reader</li>
<li>all images need amending so that the screen reader doesn’t read out the file name</li>
<li>the content isn’t as usable when you enlarge the text</li>
<div class="call-to-action">We were advised by accessibility colleagues that a sitemap was not required in this instance.</div>
</ul>
</div>

<h3 id="what-to-do-if-you-cannot-access-parts-of-this-website">What to do if you cannot access parts of this website</h3>
<p>If you need information on this website in a different format like accessible PDF, large print, easy read, audio recording or braille:</p>
<ul>
<li>email: <a href= "mailto:AnalystsUncertaintyToolkit@homeoffice.gov.uk" style="color: DARKBLUE;"><b>AnalystsUncertaintyToolkit@homeoffice.gov.uk</b></a></li>
</ul>
<p>We'll consider your request and get back to you as soon as is practicably possible.</p>

<h3 id="reporting-accessibility-problems-with-this-website">Reporting accessibility problems with this website</h3>
<p>We're always looking to improve the accessibility of this website. If you find any problems not listed on this page or think we're not meeting accessibility requirements, contact us by email on: <a href= "mailto:AnalystsUncertaintyToolkit@homeoffice.gov.uk" style="color: DARKBLUE;"><b>AnalystsUncertaintyToolkit@homeoffice.gov.uk</b></a></p>

<h3 id="enforcement-procedure">Enforcement procedure</h3>
<p>The Equality and Human Rights Commission (EHRC) is responsible for enforcing the Public Sector Bodies (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018 (the 'accessibility regulations'). If you're not happy with how we respond to your complaint, <a href="https://www.equalityadvisoryservice.com/" style="color: DARKBLUE;"><b>contact the Equality Advisory and Support Service (EASS)</b></a>.</p>

<h3 id="technical-information-about-this-websites-accessibility">Technical information about this website's accessibility</h3>
<div class="call-to-action">
<p>This website is partially compliant with the <a href="https://www.w3.org/TR/WCAG21/" style="color: DARKBLUE;"><b>Web Content Accessibility Guidelines version 2.1 </b></a>AA standard, due to the non-compliances listed below.</p>
</div>

<h3 id="how-we-tested-this-website">How we tested this website</h3>
<p>This website was last tested in January 2020. The test was carried out by accessibility experts in the Ministry of Justice and changes were made by analysts in the Department for Education.</p>

<h3 id="what-were-doing-to-improve-accessibility">What we're doing to improve accessibility</h3>
<div class="call-to-action">
<p>We are actively trying to get resource for a CSS/html expert to overcome the issues listed in the "How accessible this website is" paragraph above. This will help to ensure that this site is fully accessible. We will continue to monitor the accessibility of this website on an on-going basis and we plan to fix any accessibility issues reported to us.</p>
</div>


<div class="footer">
<b>Useful links:</b>
<br><br>
<a href="index.html">Click here to return to home page</a>
</div>