---
title: <br><br><br> 6. Conclusion
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
---

<style type="text/css">

.footer{
  position: relative; 
  margin-top: 1000px; 
  height = 100px; 
  width: 100%;
  text-align: left
}

.
</style>

This toolkit is designed to provide guidance to analysts on how to incorporate uncertainty analysis into their work, as well as setting out some high level advice to decision makers, so they know what to expect when commissioning analysis and interpreting analytical results. 
<br>

See the Case Studies for examples of applying and communicating some of the techniques listed <a href="https://analystsuncertaintytoolkit.github.io/UncertaintyWeb/case_studies.html" style="color: DARKBLUE";> <b>here</b></a>.
<br>

Additional papers that may be of interest are presented in the <a href="https://analystsuncertaintytoolkit.github.io/UncertaintyWeb/further_reading.html" style="color: DARKBLUE";> <b>Further Reading</b></a> tab. 
Your department may also have an uncertainty group who can advise on specific techniques and their implementation.
<br>

This toolkit has set out good, not best, practice, as analysis and communication must always be tailored to the audience and decision being made.
<br>

Please get in touch if you have any comments by emailing: <a href="mailto:AnalystsUncertaintyToolkit@homeoffice.gov.uk" style="color:DARKBLUE";> <b>AnalystsUncertaintyToolkit@homeoffice.gov.uk</b></a> 
<br>We also welcome your feedback via our <a href="https://www.smartsurvey.co.uk/s/P0DS1/" style="color: DARKBLUE";> <b>short feedback survey</b></a>


<div class="footer">
<b>Useful links:</b>
<br><br>
<a href="accessibility.html">Click here to see the accessibility statement</a>
<br><br>
<a href="index.html">Click here to return to home page</a>
</div>