---
title: <br><br><br> Uncertainty Toolkit for Analysts in Government
---

<style type="text/css">

#TOC {
margin-top: 100px;
}

.leftA{
float: left;
width: 100%;
font-weight: bold;
}

.rightA{
float:right;
width: 75%;
}

.leftB{
float: left;
text-align: right;
width: 23%;
}

.footer{
  position: relative; 
  margin-top: 450px; 
  height = 100px; 
  width: 100%;
  text-align: left
}

.
</style>

<div class = "rightA">
A cross government group has worked together to create a communicating and assessing uncertainty toolkit.
</div>

<div class = "rightA">
This toolkit sets out good, not best, practice, as analysis and communication must always be tailored to the audience and decision being made. 
</div>

<div class = "rightA">
<b>The toolkit is presented in the first instance as a suggested set of guidelines and we will be consulting with experts from Government, the academic community and other external bodies to develop thinking in line with the latest evidence on communicating uncertainty.</b> 
</div>
<br>

<div class = "rightA">
<br>
We welcome feedback on the content by 20th March 2020. You can get in touch by emailing: <br><a href= "mailto:AnalystsUncertaintyToolkit@homeoffice.gov.uk" style="color: DARKBLUE";> <b>AnalystsUncertaintyToolkit@homeoffice.gov.uk</b></a> 
<br>We also welcome your feedback via our <a href = "https://www.smartsurvey.co.uk/s/P0DS1/" style="color: DARKBLUE;"> <b>short feedback survey</b></a>.
<br>
</div>

<div class = "leftB">
<br>
Feedback
<br>
</div>

<div style="clear: both;"></div>

<div class = "leftB">
<br>
Is this toolkit for you?
</div>

<div class = "rightA">
<br>
This toolkit is aimed at all analysts, whether you are new to the Government or an experienced analyst looking to develop the way you communicate uncertainty to stakeholders. 
</div>

<div class = "rightA">
This document sits alongside the Aqua Book guidance on quality analysis. The Aqua Book should be read first as it describes the principles of uncertainty analysis and the processes that should be used in considering it. This is a supplementary document providing additional information for identifying, estimating and communicating uncertainty in analysis to support decisions and decision-makers.  
</div>

<div class = "rightA">
We have also provided a <a href = "https://analystsuncertaintytoolkit.github.io/UncertaintyWeb/exec.html" style="color: DARKBLUE";><b>one-page summary</b></a>.
</div>

<div class = "rightA">
1. <a href = "https://analystsuncertaintytoolkit.github.io/UncertaintyWeb/introduction.html" style="color: DARKBLUE";> <b>Introduction</b></a>
2. <a href = "https://analystsuncertaintytoolkit.github.io/UncertaintyWeb/index.html" style="color: DARKBLUE";> <b>Jointly agreeing how uncertainty should be used</b></a>
3. <a href = "https://analystsuncertaintytoolkit.github.io/UncertaintyWeb/chapter_2.html" style="color: DARKBLUE";> <b>Defining and identifying uncertainty</b></a>
4. <a href = "https://analystsuncertaintytoolkit.github.io/UncertaintyWeb/chapter_3.html" style="color: DARKBLUE";> <b>Understanding and measuring uncertainty</b></a>
5. <a href = "https://analystsuncertaintytoolkit.github.io/UncertaintyWeb/chapter_4.html" style="color: DARKBLUE";> <b>Presenting and communicating uncertainty</b></a>
6. <a href = "https://analystsuncertaintytoolkit.github.io/UncertaintyWeb/Conclusion.html" style="color: DARKBLUE";> <b>Conclusion</b></a>
7. <a href = "https://analystsuncertaintytoolkit.github.io/UncertaintyWeb/case_studies.html" style="color: DARKBLUE";> <b>Case studies</b></a>
8. <a href = "https://analystsuncertaintytoolkit.github.io/UncertaintyWeb/further_reading.html" style="color: DARKBLUE";> <b>Further reading</b></a>
9. <a href = "https://analystsuncertaintytoolkit.github.io/UncertaintyWeb/exec.html" style="color: DARKBLUE";> <b>Decision-maker summary on analytical uncertainty</b></a>
</div>

<div class="footer">
<b>Useful links:</b>
<br><br>
<a href="accessibility.html">Click here to see the accessibility statement</a>
</div>


