---
title: <br><br><br> Introduction
---


<style type="text/css">

#TOC {
margin-top: 100px;
}

.leftA{
float: left;
width: 100%;
font-weight: bold;
}

.rightA{
float:right;
width: 75%;
}

.leftB{
float: left;
width: 23%;
text-align: right;
}

.footer{
  position: relative;
  margin-top: 450px;
  height = 100px;
  width: 100%;
  text-align: left
}

.
</style>

<div style="clear: both;"></div>

<br>

<div class = "leftB">
Uncertainty analysis: understanding what you don't know
</div>

<div class = "rightA">
Uncertainty is unavoidable when making predictions about future events or impacts of decisions. Our knowledge of the present is typically  incomplete; and we can’t be sure what will happen in the future. We can reduce uncertainty due to lack of knowledge by obtaining more information, or asking experts for advice. However, we can’t eliminate uncertainty entirely, so we must find ways to describe and communicate it.
</div>

<div class = "rightA">
There is a difference between uncertainty and risk; risk typically refers to the likelihood of a future unplanned event or unintended consequence that can be assigned a numeric probability. Forecasts of risk, like other forecasts, are themselves subject to uncertainty. For example, UK Met Office predictions of the risk of rain are uncertain as to whether it will rain at all, as well as uncertainty about how much it will rain. This uncertainty is described using a range from running several forecasts from equally likely initial conditions.
</div>

<div class = "rightA">
Taking account of uncertainty – and being seen to do so – is important for public trust. We must not pretend that the consequences of a policy or decision are certain: they are always uncertain to some degree. For each option, a range of outcomes are possible. Implying certainty about one particular outcome can damage public trust when things turn out differently.
</div>


<div class = "leftB">
Why does it matter?
</div>

<div class = "rightA">
Red River Flood, Grand Forks USA, 1997
</div>

<div class = "leftB">
<b>Example</b>
</div>

<div class = "rightA">
The National Weather Service (NWS) predicted, 2 months in advance, the Red River to crest 49 feet.
</div>

<div class = "rightA">
In response, the levees were built to handle a flood of 51 feet
</div>

<div class = "rightA">
The actual flood level was 54 feet.
</div>

<div class = "rightA">
Had the NWS communicated their uncertainty (+/- 9 feet) the several $billion damages as well as the huge personal impact could have been avoided.
</div>

<div style="clear: both;"></div>

```{r fig.align="center", echo=FALSE}

comb2pngs <- function(imgs, bottom_text = NULL){
  img1 <-  grid::rasterGrob(as.raster(png::readPNG(imgs[1])),
                            interpolate = FALSE)
  img2 <-  grid::rasterGrob(as.raster(png::readPNG(imgs[2])),
                            interpolate = FALSE)
  pdp::grid.arrange(img1, img2, ncol = 2, bottom = bottom_text)
}

png1_dest <- "images/Flood_uncertainty.png"
png2_dest <- "images/Flood_damage.png"

comb2pngs(c(png1_dest, png2_dest))


```


<div class = "rightA">
This toolkit contains the following chapters:
</div>

<div class = "rightA">
Before conducting any uncertainty analysis, it is important to check that you understand how the analysis will be used. What type of decision is being made? Are you informing a debate or a final decision? This will frame how you approach the analysis and how you communicate it to your customers.
</div>

<div class = "leftB">
1. Jointly agreeing how uncertainty should be used
</div>

<div class = "rightA">
Considering the whole system that influences your analysis helps identify all possible areas where uncertainty can arise. Ensure you understand what is causing the uncertainty in your inputs and outputs, and whether this can be quantified.
</div>

<div class = "leftB">
2. Defining and identifying uncertainty
</div>

<div class = "rightA">
Before conducting uncertainty analysis, you should consider the range of possible techniques. We provide a list of the most common techniques with some examples for reference.
</div>

<div class = "leftB">
3. Understanding and measuring uncertainty
</div>

<div class = "rightA">
There is little point conducting any analysis if it has no impact, so this is perhaps the most important section. It is important to engage with your decision makers so they take account of uncertainty in any decisions they make. You should think about how you interact with the audience, tailoring your communication to different groups. This will help them to understand the consequences of uncertainty and why they should be interested in it.
</div>

<div class = "leftB">
4. Presenting and communicating uncertainty
</div>

<div class="footer">
<b>Useful links:</b>
<br><br>
<a href="accessibility.html">Click here to see the accessibility statement</a>
<br><br>
<a href="index.html">Click here to return to home page</a>
</div>

<head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<style>
  /* This is the css styling of the PopUp this can be edited to change the appearance */
#gdprPopup {
    background-color: rgba(20,20,20,0.8);
    min-height: 26px;
    font-size: 14px;
    color: #ccc;
    line-height: 26px;
    padding: 8px 0 8px 30px;
    font-family: "Trebuchet MS",Helvetica,sans-serif;
    position: fixed;
    bottom: 0;
    left: 0;
    right: 0;
    display: none;
    z-index: 9999;
}
#gdprPopup a {
    color: #4B8EE7;
    text-decoration: none;
}
#closegdprPopup {
    float: right;
    display: inline-block;
    cursor: pointer;
    height: 20px;
    width: 20px;
    margin: -15px 0 0 0;
    font-weight: bold;
}
#closegdprPopup:hover {
    color: #FFF;
}
#gdprPopup a.gdprPopupOK {
    background-color: #F1D600;
    color: #000;
    display: inline-block;
    border-radius: 5px;
    padding: 0 20px;
    cursor: pointer;
    float: right;
    margin: 0 60px 0 10px;
}
#gdprPopup a.gdprPopupOK:hover {
    background-color: #E0C91F;
}
/* End of css styling /*


</style>
</head>

<body>
<script>
// This is the js function to animate the popup //
// The value 2000 sets the length of time before it appears, this can be changed to any value (e.g 4 seconds = 4000) //
// fadeIn and fadeOut are set to 200, this can be changed to change the transition period  //

  $(document).ready(function(){
      setTimeout(function () {
          $("#gdprPopup").fadeIn(200);
       }, 2000);
      $("#closegdprPopup, .gdprPopupOK").click(function() {
          $("#gdprPopup").fadeOut(200);
      });
  });
</script>

<div id="gdprPopup">
<div id="closegdprPopup">x
</div>
  In the government we respect your concerns about privacy and value the relationship that we have with you.

  We use technology on our website to collect information that helps us enhance the experience and tailor our products to our users.

  Read the MORE INFORMATION page for further details of what is collected.
<a href="#" target="_blank">More info</a>
<a class="gdprPopupOK">That's Fine</a>
</div>

</body>
</html>
